# Generated by Django 2.1.7 on 2019-10-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='context',
            new_name='content',
        ),
    ]
